name: Build Check and Publish

on:
  push:
    branches:
      - "1.14.4"
      - "1.15.1"
    tags:
      - "!*"

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.s1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/forge_version.properties') }}
      - id: s1
        run: |
          chmod +x ./gradlew
          echo "Hello World. Generating data files."
          VAR=$(./gradlew runData --info 2>&1)
          echo "FILTERED=$(grep QUARRYPLUS_TEST ${VAR})"
          echo "::set-output name=test::${FILTERED}"
          echo "Hello World. Finished testing."
        continue-on-error: true
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Stop if test failed
        if: ${{ steps.s1.outputs.test }} != ""
        run: |
          echo "FILTERED=${FILTERED}"
          echo "Test ${{ steps.s1.outputs.test }}"
          false
      - name: Compile and Publish
        run: chmod +x ./gradlew && ./gradlew build publish --continue --warning-mode all
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
