name: Build Check and Publish

on:
  push:
    branches:
      - "1.14.4"
      - "1.15.1"
    tags:
      - "!*"

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.s1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/forge_version.properties') }}
      - id: s1
        run: |
        chmod +x ./gradlew
        echo "VAR=$(./gradlew runData --info 2>&1)"
        echo "FILTERED=$(grep ERROR_COUNT $VAR)"
        echo "::set-output name=test::${FILTERED}"
        continue-on-error: true
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Stop if test failed
        run: false
      - name: Compile and Publish
        run: chmod +x ./gradlew && ./gradlew build publish --continue --warning-mode all
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
