name: Build Check and Publish

on:
  push:
    branches:
      - "1.14.4"
      - "1.15.1"
    tags:
      - "!*"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/forge_version.properties') }}
      - name: Test
        run: chmod +x ./gradlew && ./gradlew runData -- info
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      - name: Stop if test failed
        run: false
      - name: Compile and Publish
        run: chmod +x ./gradlew && ./gradlew build publish --continue --warning-mode all
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
